/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_kevinbanegas;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class SistemaControl extends javax.swing.JFrame {

    /**
     * Creates new form SistemaControl
     */
    public SistemaControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_Cargar = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        agregarSer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreUniverso = new javax.swing.JTextField();
        idSer = new javax.swing.JTextField();
        añosSer = new javax.swing.JSpinner();
        poderSer = new javax.swing.JSpinner();
        cb_universos = new javax.swing.JComboBox<>();
        cb_razas = new javax.swing.JComboBox<>();
        crearUniverso = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nombreSer = new javax.swing.JTextField();
        crearSer = new javax.swing.JButton();
        modSer = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        idSerMod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        añosSerMod = new javax.swing.JSpinner();
        poderSerMod = new javax.swing.JSpinner();
        cb_SerMod = new javax.swing.JComboBox<>();
        cb_razasMod = new javax.swing.JComboBox<>();
        modButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombreSerMod = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb_universosMod1 = new javax.swing.JComboBox<>();
        elimSer = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        buscarSer = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        buscarSerId = new javax.swing.JTextField();
        buscarSerNombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        caracteristicasSer = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cargarGuardar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        dialog_Cargar.setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Litera-Serial", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cargando...");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, 40));
        jPanel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 370, 50));

        javax.swing.GroupLayout dialog_CargarLayout = new javax.swing.GroupLayout(dialog_Cargar.getContentPane());
        dialog_Cargar.getContentPane().setLayout(dialog_CargarLayout);
        dialog_CargarLayout.setHorizontalGroup(
            dialog_CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        dialog_CargarLayout.setVerticalGroup(
            dialog_CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        agregarSer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");
        agregarSer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel2.setText("ID");
        agregarSer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel3.setText("Poder");
        agregarSer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel4.setText("Años");
        agregarSer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel5.setText("Crear Universo");
        agregarSer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel6.setText("Raza");
        agregarSer.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));
        agregarSer.add(nombreUniverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 164, 37));
        agregarSer.add(idSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 148, 37));
        agregarSer.add(añosSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 56, 34));
        agregarSer.add(poderSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 56, 34));

        agregarSer.add(cb_universos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 187, 37));

        cb_razas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humanos", "Amantos" }));
        agregarSer.add(cb_razas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 164, 37));

        crearUniverso.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        crearUniverso.setText("Crear Universo");
        crearUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearUniversoMouseClicked(evt);
            }
        });
        crearUniverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUniversoActionPerformed(evt);
            }
        });
        agregarSer.add(crearUniverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 190, 30));

        jLabel14.setFont(new java.awt.Font("Litera-Serial", 0, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Crear Ser");
        agregarSer.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 298, 40));

        jLabel16.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel16.setText("Universo Prodecencia");
        agregarSer.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));
        agregarSer.add(nombreSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 164, 37));

        crearSer.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        crearSer.setText("Crear y Guardar");
        crearSer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearSerMouseClicked(evt);
            }
        });
        agregarSer.add(crearSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 187, 48));

        jTabbedPane1.addTab("Agregar Ser", agregarSer);

        modSer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modSerFocusGained(evt);
            }
        });
        modSer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel7.setText("Universo Prodecencia");
        modSer.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 85, -1, -1));
        modSer.add(idSerMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 114, 148, 37));

        jLabel8.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel8.setText("Raza");
        modSer.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 341, -1, -1));
        modSer.add(añosSerMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 242, 56, 34));
        modSer.add(poderSerMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 242, 56, 34));

        cb_SerMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_SerModActionPerformed(evt);
            }
        });
        modSer.add(cb_SerMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 187, 37));

        cb_razasMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humanos", "Amantos" }));
        modSer.add(cb_razasMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 370, 164, 37));

        modButton.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        modButton.setText("Modificar");
        modButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modButtonMouseClicked(evt);
            }
        });
        modSer.add(modButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 228, 187, 48));

        jLabel9.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel9.setText("Nombre");
        modSer.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 85, -1, -1));

        jLabel10.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel10.setText("ID");
        modSer.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 85, -1, -1));
        modSer.add(nombreSerMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 114, 164, 37));

        jLabel11.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel11.setText("Poder");
        modSer.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 213, -1, -1));

        jLabel12.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel12.setText("Años");
        modSer.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 213, -1, -1));

        jLabel13.setFont(new java.awt.Font("Litera-Serial", 0, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Modificar Ser");
        modSer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 298, 40));

        cb_universosMod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_universosMod1ActionPerformed(evt);
            }
        });
        modSer.add(cb_universosMod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 114, 187, 37));

        jTabbedPane1.addTab("Modificar Ser", modSer);

        elimSer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Litera-Serial", 0, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Eliminar Ser");
        elimSer.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 298, 40));

        elimSer.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 280, 60));

        jButton1.setFont(new java.awt.Font("Litera-Serial", 0, 24)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        elimSer.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 180, 70));

        jTabbedPane1.addTab("Eliminar Ser", elimSer);

        buscarSer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Litera-Serial", 0, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Buscar Ser");
        buscarSer.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 298, 40));
        buscarSer.add(buscarSerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 170, 37));
        buscarSer.add(buscarSerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, 37));

        jButton2.setText("Buscar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        buscarSer.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 170, 30));

        caracteristicasSer.setColumns(20);
        caracteristicasSer.setRows(5);
        caracteristicasSer.setWrapStyleWord(true);
        buscarSer.add(caracteristicasSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, 170));

        jLabel19.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel19.setText("ID");
        buscarSer.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel22.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel22.setText("Nombre");
        buscarSer.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jTabbedPane1.addTab("Buscar Seres", buscarSer);

        jMenu1.setText("Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        cargarGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cargarGuardar.setText("Cargar");
        cargarGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(cargarGuardar);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

    }//GEN-LAST:event_jMenu1MouseClicked

    private void cargarGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarGuardarActionPerformed

        cargarSeres();
        jProgressBar2.setMaximum(seres.size());
        Hilo h = new Hilo(jProgressBar2, seres, dialog_Cargar);
        h.start();
        dialog_Cargar.setModal(true);
        dialog_Cargar.pack();
        dialog_Cargar.setLocationRelativeTo(this);
        dialog_Cargar.setVisible(true);
        if (jProgressBar2.getMaximum() == seres.size()) {
            jProgressBar2.setValue(0);
            dialog_Cargar.setVisible(false);
        }
        dialog_Cargar.setVisible(false);
        cargarUniversos();
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_universos.getModel();
        m.removeAllElements();
        for (Universo universo : universos) {
            m.addElement(universo);
        }
        cb_universos.setModel(m);
        cb_universosMod1.setModel(m);

        DefaultComboBoxModel m1 = (DefaultComboBoxModel) cb_SerMod.getModel();
        m1.removeAllElements();
        for (Ser ser : seres) {
            m1.addElement(ser);
        }
        cb_SerMod.setModel(m1);
        jComboBox1.setModel(m1);
        JOptionPane.showMessageDialog(this, "Exito");
    }//GEN-LAST:event_cargarGuardarActionPerformed

    private void crearSerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearSerMouseClicked
        try {
            Ser s = new Ser();

            s.setAños(Integer.parseInt(añosSer.getValue().toString()));
            s.setId(Integer.parseInt(idSer.getText()));
            s.setProcedencia((Universo) cb_universos.getSelectedItem());
            s.setNombre(nombreSer.getText());
            s.setPoder(Integer.parseInt(poderSer.getValue().toString()));
            s.setRaza(cb_razas.getSelectedItem().toString());

            seres.add(s);
            JOptionPane.showMessageDialog(this, "Exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar datos", "Error", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_crearSerMouseClicked

    private void crearUniversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUniversoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearUniversoActionPerformed

    private void crearUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearUniversoMouseClicked
        try {
            if (!crearUniverso.getText().isEmpty()) {
                Universo u = new Universo();
                u.setNombre(nombreUniverso.getText());
                universos.add(u);

            } else {
                JOptionPane.showMessageDialog(this, "Error al ingresar datos", "Error", JOptionPane.WARNING_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar datos", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_crearUniversoMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        escribirSeres();
        escribirUniversos();
        escribirTodo();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void cb_SerModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_SerModActionPerformed

        Ser s = (Ser) cb_SerMod.getSelectedItem();
        if (cb_SerMod.getSelectedItem() instanceof Ser) {
            nombreSerMod.setText(s.getNombre());
            idSerMod.setText("" + s.getId());
            poderSerMod.setValue(s.getPoder());
            añosSerMod.setValue(s.getAños());
            if ("Humanos".equals(s.getRaza())) {
                cb_razasMod.setSelectedIndex(0);
            } else {
                cb_razasMod.setSelectedIndex(1);
            }
            cb_SerMod.setSelectedItem(s.getProcedencia());
        }


    }//GEN-LAST:event_cb_SerModActionPerformed

    private void cb_universosMod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_universosMod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_universosMod1ActionPerformed

    private void modSerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modSerFocusGained
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_SerMod.getModel();
        m.removeAllElements();
        for (Ser sere : seres) {
            m.addElement(sere);
        }
        cb_SerMod.setModel(m);
        jComboBox1.setModel(m);
    }//GEN-LAST:event_modSerFocusGained

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_SerMod.getModel();
        m.removeAllElements();
        for (Ser sere : seres) {
            m.addElement(sere);
        }
        cb_SerMod.setModel(m);
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void modButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modButtonMouseClicked
        try {
            int i = cb_SerMod.getSelectedIndex();
            seres.get(i).setAños(Integer.parseInt(añosSerMod.getValue().toString()));
            seres.get(i).setId(Integer.parseInt(idSerMod.getText()));
            seres.get(i).setNombre(nombreSerMod.getText());
            seres.get(i).setPoder(Integer.parseInt(poderSerMod.getValue().toString()));
            seres.get(i).setProcedencia((Universo) cb_universosMod1.getSelectedItem());
            seres.get(i).setRaza(cb_razasMod.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Modifico con Exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar datos", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_modButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int i = seres.get(jComboBox1.getSelectedIndex()).getId();
        seres.remove(jComboBox1.getSelectedIndex());
        File temp = new File("./SeresIndividuales/" + i);
        temp.delete();
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_SerMod.getModel();
        m.removeAllElements();

        for (Ser sere : seres) {
            m.addElement(sere);
        }
        cb_SerMod.setModel(m);
        jComboBox1.setModel(m);

        JOptionPane.showMessageDialog(this, "Eliminado Exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        caracteristicasSer.setText("");
        int i = 0;
        for (Ser sere : seres) {
            if (buscarSerNombre.getText().equals(sere.getNombre()) && Integer.parseInt(buscarSerId.getText()) == sere.getId()) {
                caracteristicasSer.append("Nombre: " + sere.getNombre() + "\n");
                caracteristicasSer.append("Raza: " + sere.getRaza() + "\n");
                caracteristicasSer.append("Años: " + sere.getAños() + "\n");
                caracteristicasSer.append("ID: " + sere.getId() + "\n");
                caracteristicasSer.append("Poder: " + sere.getPoder() + "\n");
                caracteristicasSer.append("Prodecencia: " + sere.getProcedencia() + "\n");
            } else {
                i++;
            }
        }
        if (i == seres.size()) {
            caracteristicasSer.append("No se encontro el ser, o no pertenece al universo. \n");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    public void cargarSeres() {
        try {
            seres = new ArrayList();
            Ser s;
            Ser = new File("./SeresIndividuales/");
            File[] seresFile = Ser.listFiles();
            for (File sere : seresFile) {
                try {
                    FileInputStream entrada
                            = new FileInputStream(sere);
                    ObjectInputStream objeto
                            = new ObjectInputStream(entrada);
                    s = (Ser) objeto.readObject();
                    seres.add(s);

                } catch (Exception e) {

                }
            }

        } catch (Exception e) {

        }
    }

    public void cargarUniversos() {
        try {
            universos = new ArrayList();
            Universo u;
            Universo = new File("./UniversosIndividuales/");
            File[] universosFile = Universo.listFiles();
            for (File uni : universosFile) {
                try {
                    FileInputStream entrada
                            = new FileInputStream(uni);
                    ObjectInputStream objeto
                            = new ObjectInputStream(entrada);
                    u = (Universo) objeto.readObject();
                    universos.add(u);

                } catch (Exception e) {

                }
            }

        } catch (Exception e) {

        }
    }

    public void escribirSeres() {
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        //Ser = new File("./SeresIndividuales/" + s.getId());
        try {
            for (Ser sere : seres) {
                try {
                    Ser = new File("./SeresIndividuales/" + sere.getId());
                    fw = new FileOutputStream(Ser);
                    bw = new ObjectOutputStream(fw);
                    bw.writeObject(sere);
                } catch (Exception e) {

                }

            }

            bw.flush();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar datos", "Error", JOptionPane.WARNING_MESSAGE);
        }

    }

    public void escribirUniversos() {
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            for (Universo u : universos) {
                try {
                    Universo = new File("./UniversosIndividuales/" + u.getNombre());
                    fw = new FileOutputStream(Universo);
                    bw = new ObjectOutputStream(fw);
                    bw.writeObject(u);
                } catch (Exception e) {

                }
            }
            bw.flush();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar datos", "Error", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
    }

    public void escribirTodo() {
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            Universo = new File("./SeresUniversos/universos.kev");
            for (Universo u : universos) {
                fw = new FileOutputStream(Universo);
                bw = new ObjectOutputStream(fw);
                bw.writeObject(u);
            }
            Ser = new File("./SeresUniversos/seres.kev");
            for (Ser sere : seres) {
                fw = new FileOutputStream(Ser);
                bw = new ObjectOutputStream(fw);
                bw.writeObject(sere);
                System.out.println(sere.getNombre());
            }
            bw.flush();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar datos", "Error", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaControl().setVisible(true);
            }
        });
    }

    private File Ser;
    private File Universo;
    private ArrayList<Ser> seres = new ArrayList();
    private ArrayList<Universo> universos = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregarSer;
    private javax.swing.JSpinner añosSer;
    private javax.swing.JSpinner añosSerMod;
    private javax.swing.JPanel buscarSer;
    private javax.swing.JTextField buscarSerId;
    private javax.swing.JTextField buscarSerNombre;
    private javax.swing.JTextArea caracteristicasSer;
    private javax.swing.JMenuItem cargarGuardar;
    private javax.swing.JComboBox<String> cb_SerMod;
    private javax.swing.JComboBox<String> cb_razas;
    private javax.swing.JComboBox<String> cb_razasMod;
    private javax.swing.JComboBox<String> cb_universos;
    private javax.swing.JComboBox<String> cb_universosMod1;
    private javax.swing.JButton crearSer;
    private javax.swing.JButton crearUniverso;
    private javax.swing.JDialog dialog_Cargar;
    private javax.swing.JPanel elimSer;
    private javax.swing.JTextField idSer;
    private javax.swing.JTextField idSerMod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modButton;
    private javax.swing.JPanel modSer;
    private javax.swing.JTextField nombreSer;
    private javax.swing.JTextField nombreSerMod;
    private javax.swing.JTextField nombreUniverso;
    private javax.swing.JSpinner poderSer;
    private javax.swing.JSpinner poderSerMod;
    // End of variables declaration//GEN-END:variables
}
